#!/usr/bin/env bash

# https://hub.docker.com/r/linuxserver/sonarr/

root=$(cd "$(dirname "$0")" && pwd)
data=$root/data

media=$HOME/windrive/media
while ! [ $(ls "$media" | wc -l) -gt 0 ]; do
  echo waiting for media...
  sleep 0.5
done

torrents=$HOME/windata/torrents
while ! [ $(ls "$torrents" | wc -l) -gt 0 ]; do
  echo waiting for torrents...
  sleep 0.5
done

ng=$HOME/windata/ng
while ! [ $(ls "$ng" | wc -l) -gt 0 ]; do
  echo waiting for ng...
  sleep 0.5
done

winpc=`getent hosts winpc | awk '{ print $1 }'`
[[ "$winpc" ]] || {
  echo "failed to get IP of winpc" >&2
  exit 1
}

exec docker run --rm \
  --network mediadl \
  --name sonarr \
  --add-host=winpc:$winpc \
  -v $data/config:/config \
  -v $torrents:/torrents:ro \
  -v $ng:/ng \
  -v $media/series:/series \
  -e PUID=$UID -e PGID=$UID \
  -e TZ=Europe/Paris \
  -p 8989:8989 \
  linuxserver/sonarr:develop
