#!/usr/bin/env bash

services=(
  influxdb
  prices
  prices_websocket
  grafana
  redis
  ngrok

  # syncthing
  # radarr
  # lidarr
  # bazarr
  # sonarr
  # jackett
  # hydra
  # sabnzbd
)

exec mg "$@" "${services[@]}"
