#!/usr/bin/env bash

root=$(cd "$(dirname "$0")" && pwd)

port=3000:3000

data=/var/lib/grafana
data_local=$root/data

log=/var/log/grafana
log_local=$root/log

exec docker run --rm \
  -p $port \
  --network influx \
  --name grafana \
  --user $UID:$GID \
  -e GF_PATHS_DATA=$data  -v $data_local:$data \
  -e GF_PATHS_LOGS=$log   -v $log_local:$log \
  grafana/grafana
