#!/usr/bin/env bash

# https://hub.docker.com/r/linuxserver/jackett/

root=$(cd "$(dirname "$0")" && pwd)
data=$root/data

exec docker run --rm \
  --network mediadl \
  --name jackett \
  -v $data:/config \
  -e PUID=$UID -e PGID=$UID \
  -e TZ=Europe/Paris \
  -p 9117:9117 \
  linuxserver/jackett:development
