VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.6.3'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'yungsang/boot2docker'

  config.vm.provider 'virtualbox' do |p|
    p.memory = 2048
    p.cpus = 3
  end

  config.vm.network :forwarded_port, guest: 80, host: 1080, auto_correct: true

  # config.vm.synced_folder '.', '/vagrant'

  # config.vm.provision :docker do |d|
  #   d.pull_images "yungsang/busybox"
  #   d.run "simple-echo",
  #     image: "yungsang/busybox",
  #     args: "-p 8080:8080",
  #     cmd: "nc -p 8080 -l -l -e echo hello world!"
  # end
  # config.vm.network :forwarded_port, guest: 8080, host: 8080
end
