#!/usr/bin/env bash

root=`dirname "$0"`

cd "$root"

exec docker run --rm \
  --name telegraf \
  --network influx \
  -v $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro \
  -e HOST_PROC=/host/proc -v /proc:/host/proc:ro \
  -v /var/run/docker.sock:/var/run/docker.sock \
  telegraf:1.9.2 \
  telegraf
