#!/usr/bin/env bash

root=$(cd "$(dirname "$0")" && pwd)
data=$root/data

# https://hub.docker.com/_/postgres

exec docker run --rm \
  --network postgres \
  --name postgres \
  -v $data:/var/lib/postgresql/data \
  --user $UID:$UID \
  postgres:alpine
