#!/usr/bin/env bash

root=$(cd "$(dirname "$0")" && pwd)
data=$root/data
port=6379

# https://hub.docker.com/_/redis

exec docker run --rm \
  --network redis \
  --name redis \
  -v $data:/data \
  -p $port:$port \
  --user $UID:$UID \
  redis
